"""Generate the Phase 6 DOD cross-method comparison report.

Builds a deterministic synthetic 20-asset universe (3 common factors plus
idiosyncratic noise, 756 daily bars ~ 3 years), runs
``core_trading.portfolio.comparison.compare_methods`` and writes
``docs/PHASE6_METHOD_COMPARISON.md``.

Usage:
    ./.venv/Scripts/python.exe tools/phase6_comparison_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# cvxpy MUST be imported before pandas on this Windows environment: its
# compiled core access-violates (0xC0000005) when first imported into a
# process that already loaded pandas.  Alphabetical import order happens
# to be the correct load order here; do not "clean up" this block.
import cvxpy  # noqa: F401
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from core_trading.portfolio.comparison import (  # noqa: E402
    compare_methods,
    comparison_report,
)

SEED = 20260604
N_ASSETS = 20
N_BARS = 756
N_FACTORS = 3


def build_universe() -> pd.DataFrame:
    """Deterministic 3-factor synthetic daily-return universe."""
    rng = np.random.default_rng(SEED)
    loadings = rng.uniform(0.3, 1.2, size=(N_ASSETS, N_FACTORS))
    factor_vols = np.array([0.010, 0.006, 0.004])
    factor_means = np.array([0.0004, 0.0001, 0.0000])
    idio_vols = rng.uniform(0.005, 0.015, size=N_ASSETS)
    alpha = rng.uniform(-0.0002, 0.0005, size=N_ASSETS)

    factors = rng.standard_normal((N_BARS, N_FACTORS)) * factor_vols + factor_means
    idio = rng.standard_normal((N_BARS, N_ASSETS)) * idio_vols
    data = factors @ loadings.T + idio + alpha

    index = pd.date_range("2023-01-02", periods=N_BARS, freq="B")
    columns = [f"A{i:02d}" for i in range(N_ASSETS)]
    return pd.DataFrame(data, index=index, columns=columns)


def main() -> int:
    """Run the comparison and write the report document."""
    returns = build_universe()
    result = compare_methods(returns, risk_aversion=4.0, oos_fraction=0.5)
    table = comparison_report(result)

    doc = "\n".join(
        [
            "# Phase 6 Cross-Method Comparison (DOD)",
            "",
            "Generated by `tools/phase6_comparison_report.py` "
            f"(seed {SEED}, deterministic).",
            "",
            f"Universe: {N_ASSETS} synthetic assets, {N_BARS} daily bars, "
            f"{N_FACTORS}-factor structure plus idiosyncratic noise.",
            "Mandate: long-only, fully invested.  Inputs: Ledoit-Wolf",
            "covariance and Bayes-Stein means estimated on the fit window",
            "only; the held-out half scores each method out of sample.",
            "",
            "```",
            table,
            "```",
            "",
            "## Reading the table",
            "",
            "- `oos_vol` / `oos_shrp` / `max_dd`: annualised out-of-sample",
            "  volatility, Sharpe and maximum drawdown of the FIT-WINDOW",
            "  weights held through the evaluation window.",
            "- `max_w`, `hhi`, `eff_n`: weight concentration; `eff_n` is the",
            "  effective number of positions 1/HHI.",
            "- `max_rc`: largest fractional risk contribution under the",
            "  fit-window covariance.  Risk parity pins every contribution",
            "  to 1/N = 0.05 by construction; MVO concentrates risk in its",
            "  conviction names.",
            "- `ms`: fit-window runtime per method.  The Phase 6 DOD gate",
            "  (valid 20-asset weights in < 1 s) holds for every method.",
            "",
            "## Expected pattern (and what to check on real data)",
            "",
            "- Minimum variance and risk parity deliver the lowest OOS",
            "  volatility; equal weight carries the most.",
            "- MVO shows the highest weight AND risk concentration -- the",
            "  estimation-error amplification that Phases 6.1/6.5 mitigate",
            "  with shrinkage, resampling and DRO.",
            "- HRP sits between risk parity and min-variance: cluster-aware",
            "  diversification without matrix inversion.",
            "",
        ]
    )

    out_path = REPO_ROOT / "docs" / "PHASE6_METHOD_COMPARISON.md"
    out_path.write_text(doc, encoding="ascii", newline="\n")
    sys.stdout.write(f"wrote {out_path}\n")
    sys.stdout.write(table + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
