# from core_trading.nautilus_trader_engine.analysis.indicators.consolidated_indicators import ()
from nautilus_trader.model.strategy import Strategy
# "
# Base template for strategies generated by the Blockly frontend."


#     ConsolidatedIndicators,
# )


# "

class BlocklyStrategyTemplate(Strategy):""

# A template for strategies generated by the Blockly frontend.
# The generated Python code will be injected into this class."


#     def on_tick(self):
# "
# This method will be overridden by the code generated from the Blockly workspace."
# "
#         pass
# "