"""Cross-method portfolio comparison (Phase 6 DOD deliverable).

Runs the Phase 6 optimisers -- equal weight, minimum variance, constrained
MVO (Bayes-Stein means + Ledoit-Wolf covariance), HRP and risk parity --
on the SAME universe under the same long-only fully-invested mandate, and
reports the metrics that distinguish them:

* an out-of-sample split (fit on the first ``1 - oos_fraction`` of the
  panel, evaluate on the rest) producing annualised OOS volatility,
  Sharpe and maximum drawdown -- the honest comparison de Prado (2016)
  insists on, since in-sample MVO always "wins";
* weight concentration: max weight, Herfindahl-Hirschman index and its
  reciprocal (the effective number of positions);
* risk concentration: the largest fractional risk contribution under the
  fit-window Ledoit-Wolf covariance (risk parity minimises this by
  construction; MVO routinely concentrates it);
* fit-window runtime per method (the < 1 s DOD gate, measured on the
  same call the report tabulates).

:func:`comparison_report` renders the result as an ASCII table for the
committed Phase 6 report document
(``docs/PHASE6_METHOD_COMPARISON.md``, generated by
``tools/phase6_comparison_report.py``).

.. warning::
    Windows entrypoint rule: ``import cvxpy`` before pandas in any
    process that calls :func:`compare_methods` (it solves MVO QPs) --
    see the warning in :mod:`core_trading.portfolio.mvo`.

References
----------
  * Lopez de Prado, M. (2016). "Building Diversified Portfolios that
    Outperform Out of Sample."
    Journal of Portfolio Management, 42(4), 59-69.
  * DeMiguel, V., Garlappi, L. & Uppal, R. (2009). "Optimal Versus Naive
    Diversification." Review of Financial Studies, 22(5), 1915-1953.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from core_trading.portfolio.covariance import ledoit_wolf_covariance
from core_trading.portfolio.hrp import hrp_weights
from core_trading.portfolio.mvo import (
    MVOConfig,
    bayes_stein_means,
    mean_variance_weights,
    min_variance_weights,
)
from core_trading.portfolio.risk_parity import (
    risk_contributions,
    risk_parity_weights,
)

__all__ = [
    "MethodComparison",
    "compare_methods",
    "comparison_report",
]

_METHODS = ("equal", "min_variance", "mvo", "hrp", "risk_parity")


# ---------------------------------------------------------------------------
# Result DTO
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class MethodComparison:
    """Cross-method comparison on one universe.

    Attributes
    ----------
    metrics:
        One row per method; columns: ``oos_vol_ann``, ``oos_sharpe_ann``,
        ``oos_max_drawdown``, ``max_weight``, ``hhi``, ``effective_n``,
        ``max_risk_contribution``, ``runtime_ms``.
    weights:
        Assets x methods weight matrix from the fit window.
    n_fit:
        Bars in the fit window.
    n_oos:
        Bars in the evaluation window.
    ann_factor:
        Annualisation factor used (bars per year).
    """

    metrics: pd.DataFrame = field(compare=False)
    weights: pd.DataFrame = field(compare=False)
    n_fit: int
    n_oos: int
    ann_factor: float


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _max_drawdown(returns: np.ndarray) -> float:
    """Maximum peak-to-trough drawdown of a compounded return path."""
    wealth = np.cumprod(1.0 + returns)
    running_peak = np.maximum.accumulate(wealth)
    drawdowns = wealth / running_peak - 1.0
    return float(drawdowns.min())


def _oos_stats(
    weights: np.ndarray, oos: np.ndarray, ann_factor: float
) -> tuple[float, float, float]:
    """Annualised OOS volatility / Sharpe and max drawdown of a weight vector."""
    portfolio = oos @ weights
    vol = float(portfolio.std(ddof=1)) * float(np.sqrt(ann_factor))
    mean = float(portfolio.mean())
    sharpe = (
        0.0
        if portfolio.std(ddof=1) <= 0.0
        else mean / float(portfolio.std(ddof=1)) * float(np.sqrt(ann_factor))
    )
    return vol, sharpe, _max_drawdown(portfolio)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compare_methods(
    returns: pd.DataFrame,
    *,
    risk_aversion: float = 4.0,
    oos_fraction: float = 0.5,
    ann_factor: float = 252.0,
) -> MethodComparison:
    """Fit every Phase 6 method on the same universe and compare.

    The panel is split chronologically: the first part estimates inputs
    (Ledoit-Wolf covariance for every estimator-consuming method;
    Bayes-Stein means for MVO) and produces weights under a long-only,
    fully-invested mandate; the held-out part scores them.

    Parameters
    ----------
    returns:
        NaN-free returns panel (DatetimeIndex rows x asset columns), at
        least 4 rows so both windows hold >= 2 bars.
    risk_aversion:
        Gamma for the constrained-MVO utility.
    oos_fraction:
        Fraction of rows held out for evaluation, in (0, 1).
    ann_factor:
        Bars per year for annualisation (> 0).

    Returns
    -------
    MethodComparison

    Raises
    ------
    ValueError
        On an invalid panel or parameters (split windows need >= 2 bars
        each; the fit window must also satisfy the estimators'
        requirements, e.g. Bayes-Stein needs T >= N + 3).
    """
    if not 0.0 < oos_fraction < 1.0:
        raise ValueError(f"oos_fraction must be in (0, 1), got {oos_fraction}")
    if not np.isfinite(ann_factor) or ann_factor <= 0.0:
        raise ValueError(
            f"ann_factor must be a finite positive float, got {ann_factor}"
        )
    if returns.isnull().any().any():
        raise ValueError("returns panel contains NaN values.")
    n_obs = returns.shape[0]
    split = int(round(n_obs * (1.0 - oos_fraction)))
    if split < 2 or n_obs - split < 2:
        raise ValueError(
            f"panel too short to split: {n_obs} rows at "
            f"oos_fraction={oos_fraction} leaves fit={split}, "
            f"oos={n_obs - split} (both need >= 2)."
        )

    fit = returns.iloc[:split]
    oos = returns.iloc[split:]
    oos_arr = oos.to_numpy(dtype=float)
    assets = list(returns.columns)
    n_assets = len(assets)

    sigma = ledoit_wolf_covariance(fit).covariance
    mu = bayes_stein_means(fit).means
    mvo_config = MVOConfig(risk_aversion=risk_aversion, long_only=True)

    weight_columns: dict[str, pd.Series] = {}
    runtimes: dict[str, float] = {}

    start = time.perf_counter()
    weight_columns["equal"] = pd.Series(
        np.full(n_assets, 1.0 / n_assets), index=assets
    )
    runtimes["equal"] = time.perf_counter() - start

    start = time.perf_counter()
    weight_columns["min_variance"] = min_variance_weights(sigma, mvo_config).weights
    runtimes["min_variance"] = time.perf_counter() - start

    start = time.perf_counter()
    weight_columns["mvo"] = mean_variance_weights(mu, sigma, mvo_config).weights
    runtimes["mvo"] = time.perf_counter() - start

    start = time.perf_counter()
    weight_columns["hrp"] = hrp_weights(sigma).weights
    runtimes["hrp"] = time.perf_counter() - start

    start = time.perf_counter()
    weight_columns["risk_parity"] = risk_parity_weights(sigma).weights
    runtimes["risk_parity"] = time.perf_counter() - start

    rows: list[dict[str, float]] = []
    for method in _METHODS:
        w_series = weight_columns[method]
        w = w_series.to_numpy(dtype=float)
        vol, sharpe, max_dd = _oos_stats(w, oos_arr, ann_factor)
        hhi = float((w**2).sum())
        rc = risk_contributions(w_series, sigma)
        rows.append(
            {
                "oos_vol_ann": vol,
                "oos_sharpe_ann": sharpe,
                "oos_max_drawdown": max_dd,
                "max_weight": float(w.max()),
                "hhi": hhi,
                "effective_n": 1.0 / hhi,
                "max_risk_contribution": float(rc.max()),
                "runtime_ms": runtimes[method] * 1e3,
            }
        )

    metrics = pd.DataFrame(rows, index=list(_METHODS))
    weights = pd.DataFrame(weight_columns, index=assets)
    return MethodComparison(
        metrics=metrics,
        weights=weights[list(_METHODS)],
        n_fit=int(split),
        n_oos=int(n_obs - split),
        ann_factor=float(ann_factor),
    )


def comparison_report(comparison: MethodComparison) -> str:
    """Render a MethodComparison as an ASCII table block.

    Parameters
    ----------
    comparison:
        Result of :func:`compare_methods`.

    Returns
    -------
    str
        Multi-line ASCII report (no Unicode -- terminal-portable).
    """
    m = comparison.metrics
    header = (
        f"{'method':<14}"
        f"{'oos_vol':>9}"
        f"{'oos_shrp':>10}"
        f"{'max_dd':>9}"
        f"{'max_w':>8}"
        f"{'hhi':>8}"
        f"{'eff_n':>8}"
        f"{'max_rc':>8}"
        f"{'ms':>8}"
    )
    lines = [
        f"fit bars: {comparison.n_fit}   oos bars: {comparison.n_oos}   "
        f"annualisation: {comparison.ann_factor:g} bars/yr",
        "",
        header,
        "-" * len(header),
    ]
    for method, row in m.iterrows():
        lines.append(
            f"{str(method):<14}"
            f"{row['oos_vol_ann']:>9.4f}"
            f"{row['oos_sharpe_ann']:>10.3f}"
            f"{row['oos_max_drawdown']:>9.4f}"
            f"{row['max_weight']:>8.4f}"
            f"{row['hhi']:>8.4f}"
            f"{row['effective_n']:>8.2f}"
            f"{row['max_risk_contribution']:>8.4f}"
            f"{row['runtime_ms']:>8.1f}"
        )
    return "\n".join(lines)
